server {
    listen       80;
    server_name  localhost;

    # 根目录指向数据卷
    root   /usr/share/nginx/html;
    
    # 开启 Gzip 压缩
    gzip on;
    gzip_types text/plain application/xml text/css application/javascript image/svg+xml;

    location / {
        # === 跨域设置 (CORS) ===
        # 允许任何网站引用这里的图片
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';

        # === 缓存设置 ===
        # 客户端缓存 30 天
        expires 30d;
        
        try_files $uri $uri/ =404;
    }
}
